-- 제약조건 -> 컬럼에 원치않는 데이터가 입력,삭제, 수정되는걸 방지하게 만든 조건
-- Primary Key -> 테이블 고유 키
-- Unique -> 중복 X null O
-- Not Null -> 널값 안됨
-- Foreign Key -> 참조하는 테이블의 PK를 넣어놓은 컬럼, 중복/null 가능
-- Check -> 컬럼에 대한 데이터 제한

-- 제약조건을 확인하는 명령문 or 마우스로 확인
SELECT * FROM USER_CONSTRAINTS;
DROP TABLE DEPT22;
CREATE TABLE DEPT22 (
    dept_NO number(2)       CONSTRAINT DEPT2_DEPT_NO_PK Primary KEY,
    dept_name VARCHAR2(30)  CONSTRAINT DEPT2_DEPT_NAME_NN NOT NULL,
    DEPT_DATE DATE          DEFAULT SYSDATE, --> 아무것도 값 들어가지 않았을때 지정되는 값
    DEPT_PHONE VARCHAR2(30) CONSTRAINT DEPT2_DEPT_PHONE_UK Unique,
    DEPT_GENDER CHAR(1)     CONSTRAINT DEPT2_DEPT_GENDER_CK CHECK(DEPT_GENDER IN ('F','M')), --> WHERE 절에 해당
    LOCA_ID NUMBER(4)       CONSTRAINT DEPT2_LOCA_ID_FK REFERENCES LOCATIONS(LOCATION_ID)
);
DESC LOCATIONS;

--------------  이렇게 만들어도 만들어지긴 함 대신 이름이 SYSㅁㅁㅁㅁ 으로 만들어짐짐
DROP TABLE DEPTS22;
SELECT * FROM USER_CONSTRAINTS;
DROP TABLE DEPT22;
CREATE TABLE DEPT22 (
    dept_NO number(2)       Primary KEY,
    dept_name VARCHAR2(30)  NOT NULL,
    DEPT_DATE DATE          DEFAULT SYSDATE, --> 아무것도 값 들어가지 않았을때 지정되는 값
    DEPT_PHONE VARCHAR2(30) Unique,
    DEPT_GENDER CHAR(1)     CHECK(DEPT_GENDER IN ('F','M')), --> WHERE 절에 해당
    LOCA_ID NUMBER(4)       REFERENCES LOCATIONS(LOCATION_ID)
);

DESC DEPT22;

INSERT INTO DEPT22(DEPT_NO,DEPT_NAME,DEPT_PHONE,DEPT_GENDER,LOCA_ID)
VALUES (1,NULL,'010...','F',1700); -- NOT NULL 위배

INSERT INTO DEPT22(DEPT_NO,DEPT_NAME,DEPT_PHONE,DEPT_GENDER,LOCA_ID)
VALUES (1,'HONG','010...','X',1700); -- CHECK 제약 위배

INSERT INTO DEPT22(DEPT_NO,DEPT_NAME,DEPT_PHONE,DEPT_GENDER,LOCA_ID)
VALUES (1,'HONG','010...','F',100); -- FK 제약 위배

INSERT INTO DEPT22(DEPT_NO,DEPT_NAME,DEPT_PHONE,DEPT_GENDER,LOCA_ID)
VALUES (1,'HONG','010...','F',1700); 

INSERT INTO DEPT22(DEPT_NO,DEPT_NAME,DEPT_PHONE,DEPT_GENDER,LOCA_ID)
VALUES (2,'HONG','010...','F',1700); -- FK 제약 위배






