-- 컨트롤 + -> 빠른주석

SELECT * FROM EMPLOYEES;
SELECT * FROM DEPARTMENTS;
SELECT * FROM LOCATIONS;
-- 특정 컬럼만 조회시, 나열
SELECT * FROM JOBS;

SELECT EMPLOYEE_ID, FIRST_NAME, PHONE_NUMBER FROM EMPLOYEES;
-- 문자, 날짜는 왼쪽으로 표시, 숫자는 오른쪽
SELECT FIRST_NAME, HIRE_DATE, SALARY, COMMISSION_PCT FROM EMPLOYEES;

SELECT FIRST_NAME, SALARY, SALARY+SALARY*0.1 FROM EMPLOYEES;

-- 컬럼 별칭 ALIAS
SELECT FIRST_NAME AS 이름, SALARY 급여, SALARY*1.1 AS 최종_급여 FROM EMPLOYEES;

-- 문자열 붙히기
SELECT FIRST_NAME|| '''님의 급여는' || SALARY|| '$ 입니다' AS SALARY FROM EMPLOYEES;

-- disctint
SELECT DISTINCT DEPARTMENT_ID FROM EMPLOYEES;
SELECT DISTINCT FIRST_NAME, DEPARTMENT_ID FROM EMPLOYEES; --조회된 데이터 기준으로 중복을 제거하겠다
--ROWID(데이터 주소), ROWNUM(데이터 조회된 순서)
SELECT EMPLOYEE_ID, FIRST_NAME, ROWID, ROWNUM FROM EMPLOYEES;


SELECT FIRST_NAME, JOB_ID FROM EMPLOYEES WHERE JOB_ID = 'IT_PROG';

SELECT * FROM EMPLOYEES WHERE SALARY BETWEEN 10000 AND 15000;
SELECT * FROM EMPLOYEES WHERE HIRE_DATE BETWEEN '03/01/01' AND '03/12/31';

SELECT * FROM EMPLOYEES WHERE DEPARTMENT_ID IN (50,60,70);
SELECT * FROM EMPLOYEES WHERE JOB_ID IN ('IT_PROG', 'AD_VP');


SELECT * FROM EMPLOYEES WHERE SALARY >= 15000;
SELECT * FROM EMPLOYEES WHERE SALARY < 10000 ;
SELECT * FROM EMPLOYEES WHERE department_id <> 50 ;
SELECT * FROM EMPLOYEES WHERE FIRST_NAME = 'Steven';
SELECT * FROM employees WHERE HIRE_DATE <= '04/01/30';
-- 7. 보너스를 받는 사원의 이름과 직무, 보너스율을 출력하세요.
-- 8. 2003년도 입사한 사원의 이름과 입사일 그리고 급여를 출력하세요.(BETWEEN 연산자 사용)


SELECT EMPLOYEE_ID,FIRST_NAME,LAST_NAME,HIRE_DATE,SALARY FROM EMPLOYEES ;
SELECT FIRST_NAME||LAST_NAME AS name FROM EMPLOYEES;
SELECT * FROM EMPLOYEES WHERE DEPARTMENT_ID IN 50;
SELECT FIRST_NAME,LAST_NAME,DEPARTMENT_ID,MANAGER_ID FROM EMPLOYEES WHERE DEPARTMENT_ID IN 50;
SELECT FIRST_NAME||LAST_NAME AS 이름, SALARY+300, SALARY FROM EMPLOYEES;
SELECT FIRST_NAME||LAST_NAME AS 이름, SALARY FROM EMPLOYEES WHERE SALARY > 10000;
SELECT FIRST_NAME||LAST_NAME AS 이름, JOB_ID, COMMISSION_PCT FROM EMPLOYEES WHERE COMMISSION_PCT is not null;
SELECT FIRST_NAME||LAST_NAME AS 이름, HIRE_DATE, SALARY FROM EMPLOYEES WHERE HIRE_DATE BETWEEN '03/01/01' AND '03/12/31';

-- 9. 2003년도 입사한 사원의 이름과 입사일 그리고 급여를 출력하세요.(LIKE 연산자 사용)

SELECT FIRST_NAME||LAST_NAME AS 이름, HIRE_DATE, SALARY FROM EMPLOYEES WHERE HIRE_DATE LIKE '03%';

-- 10. 모든 사원의 이름과 급여를 급여가 많은 사원부터 적은 사원순서로 출력하세요.

SELECT FIRST_NAME||LAST_NAME AS 이름, SALARY FROM EMPLOYEES ORDER BY SALARY DESC;
-- 11. 위 질의를 60번 부서의 사원에 대해서만 질의하세요. (컬럼: department_id)

SELECT FIRST_NAME||LAST_NAME AS 이름, SALARY, DEPARTMENT_ID FROM EMPLOYEES WHERE DEPARTMENT_ID in 60 ORDER BY SALARY DESC;
-- 12. 직무아이디가 IT_PROG 이거나, SA_MAN인 사원의 이름과 직무아이디를 출력하세요.

SELECT FIRST_NAME||LAST_NAME AS 이름, DEPARTMENT_ID FROM EMPLOYEES WHERE JOB_ID = 'IT_PROG' OR JOB_ID = 'SA_MAN';
-- 13. Steven King 사원의 정보를 “Steven King 사원의 급여는 24000달러 입니다” 형식으로 출력하세요.

SELECT FIRST_NAME||LAST_NAME||'사원의 급여는'||SALARY||'달러 입니다' FROM EMPLOYEES WHERE FIRST_NAME = 'Steven' AND LAST_NAME = 'King';
-- 14. 매니저(MAN) 직무에 해당하는 사원의 이름과 직무아이디를 출력하세요. (컬럼:job_id)
SELECT FIRST_NAME||LAST_NAME AS 이름, JOB_ID FROM EMPLOYEES WHERE JOB_ID LIKE '%MAN%';
-- 15. 매니저(MAN) 직무에 해당하는 사원의 이름과 직무아이디를 직무아이디 순서대로 출력하세요.
SELECT FIRST_NAME||LAST_NAME AS 이름, JOB_ID FROM EMPLOYEES WHERE JOB_ID LIke '%MAN%' ORDER BY JOB_ID;
-- • 제한시간 : 50분
-- • EMPLOYEES 테이블 데이터를 출력해야 합니다